/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Sep 21 2026
 * Processor: PIC18F4550
 * Compiler:  MPLAB C18
 */

#include <p18f4550.h>

void main()
 { 
   // Write your code here
   while (1)
      ;
 }
